name = "infrastruktur-jakarta-api"
main = "src/index.ts"
compatibility_date = "2026-05-14"
compatibility_flags = [ "nodejs_compat", "nodejs_compat_populate_process_env" ]
minify = true
workers_dev = false

[[routes]]
pattern = "infrastruktur-jakarta-api.ezdev.xyz"
custom_domain = true

[observability]
enabled = true

[vars]
PORT = "3000"
SUPABASE_URL = "https://dummy.supabase.co"
SUPABASE_SERVICE_KEY="your-supabase-service-key"
RATE_LIMIT_WINDOW_MS = "60000"
RATE_LIMIT_MAX = "100"
RESEND_API_KEY="your_resend_api_key_here"
EMAIL_FROM="JakInfra <noreply@xxx.com>"